AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app
  
  Root stack for application

Resources:
  Database:
    Type: AWS::Serverless::Application
    Properties:
      Location: db/template.yaml

  Functions:
    Type: AWS::Serverless::Application
    Properties:
      Location: api/template.yaml
      Parameters:
        CounterStorage: !GetAtt Database.Outputs.CounterStorage

  Routers:
    Type: AWS::Serverless::Application
    Properties:
      Location: router/template.yaml
      Parameters:
        S3WebsiteURL: !GetAtt Database.Outputs.S3Website